### ISSUE TITLE
List object has no attribute shape

### ISSUE THREAD

**Issue by phonggx** [SatyaDewangan05/sadtalker#1]
Hi there, im dig in to your work, but seem i had some trouble, could you pls check it out for me.
At this snipet code
` for batch in train_loader:
            print(len(batch))
            print('audiox: ', batch[0].shape)
            print('ref: ', batch[1].shape)
            print('ratio: ', batch[2].shape)
            print('label: ', batch[3].shape)
            break
`
i face this error : `List object has no attribute shape`, i had add this:  batch = np.array(batch) after first print, it can pass here, befor in to this line : trainer.fit(lightning_model, train_loader), in here i face : `[RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [...]`. Did i have sth wrong ? Can you explain ?

**Comment by SatyaDewangan05** [comment]
I had the same issue earlier but it fing out to be the problem is with the array, when you directly pass the array to dataloader in `train.py` then the dataloader will start mapping the dataset from 0th index e.g. if data shape is [1, 10, 64] then the array you'll get at `audio2exp.py` is [10, 64]. Use `np.expand_dims(arr, axis=0) ` so then data will be [1, 1,  10, 64] and now you'll get [1, 10, 64] at `audio2exp.py`.

To debug it further, you can try to print the length of the array you getting at `audio2exp.py` and check the length of sub element in the array then you'll have an idea of what's happening.

**Comment by phonggx** [comment]
> I had the same issue earlier but it fing out to be the problem is with the array, when you directly pass the array to dataloader in `train.py` then the dataloader will start mapping the dataset from 0th index e.g. if data shape is [1, 10, 64] then the array you'll get at `audio2exp.py` is [10, 64]. Use `np.expand_dims(arr, axis=0) ` so then data will be [1, 1, 10, 64] and now you'll get [1, 10, 64] at `audio2exp.py`.
> 
> To debug it further, you can try to print the length of the array you getting at `audio2exp.py` and check the length of sub element in the array then you'll have an idea of what's happening.

Tks, let me try and update later

**Comment by phonggx** [comment]
after do this :
`dataset = np.expand_dims(dataset, axis=0)`
and pass dataset to `Dataloader`, it return `train_loader`, continue pass it to `expNet.new_train`, i faced this new error : 
`TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found object`, i had do my own research to fix this, think about transform it with `torchvision.transforms`, but seem not work, can u recheck this for me ? tks

**Comment by SatyaDewangan05** [comment]
can you tell me the shape of data before passing it to dataloader?

**Comment by phonggx** [comment]
> can you tell me the shape of data before passing it to dataloader?

yes, this is shape of `dataset` after expand : `(1, 32, 25, 4)`

**Comment by SatyaDewangan05** [comment]
explore the data that you're passing, it seems that you're passing object (i.e. dictionary).

**Comment by phonggx** [comment]
> explore the data that you're passing, it seems that you're passing object (i.e. dictionary).

you mean my `dataset` is object ? i ditn't think so, here is my running code result, i have not modify `audio2exp.py` can you pls check this :
<img width="1439" alt="image" src="https://github.com/SatyaDewangan05/sadtalker/assets/39937935/cea71691-c399-4941-a696-aee47ca66ea6">

**Comment by phonggx** [comment]
it fixed by flattened audiox, from 5D to 4D, when you have audiox tensor shape : [batch_size, num_frames, channels, height, width], do [batch_size * num_frames, channels, height, width]. It will work

**Comment by SatyaDewangan05** [comment]
Is it working now, my code is also not completely ready so did you find it useful?
